loki:
#  schemaConfig:
 #   configs:
 #     - from: "2024-09-01"
 #       store: tsdb
 #       object_store: s3
 #       schema: v14
 #       index:
 #         prefix: loki_index_
 #         period: 24h
  ingester:
    chunk_encoding: snappy
  tracing:
    enabled: true
  querier:
    max_concurrent: 4

  storage:
    type: s3
    bucketNames:
      chunks: "enterprise-logs-chunks"
      ruler: "enterprise-logs-ruler"
      admin: "enterprise-logs-admin"
    s3:
      # s3 URL can be used to specify the endpoint, access key, secret key, and bucket name
      #s3: s3://access_key:secret_access_key@custom_endpoint/bucket_name
      # AWS endpoint URL
      endpoint: minio.metrics.svc.cluster.local:9000 
      # AWS secret access key
      secretAccessKey: "enterprise-metrics" 
      # AWS access key ID
      accessKeyId: "${MIMIRS3KEY}" 
      # Forces the path style for S3 (true/false)
      s3ForcePathStyle: false
      # Allows insecure (HTTP) connections (true/false)
      insecure: false
      # HTTP configuration settings
      http_config: {}

deploymentMode: SimpleScalable

backend:
  replicas: 3
read:
  replicas: 3
write:
  replicas: 3

# Disable minio storage
minio:
  enabled: false

# Zero out replica counts of other deployment modes
singleBinary:
  replicas: 0

ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0

monitoring:
  selfMonitoring:
    enabled: false
grafanaAgent:
  installOperator: false
